#!/usr/bin/env bash
# One-shot Spotify OAuth (Authorization Code flow) to mint a refresh token and
# write deploy/secrets.yaml. Run LOCALLY once, on a machine with a browser.
#
#   SPOTIFY_CLIENT_ID=... SPOTIFY_CLIENT_SECRET=... ./scripts/spotify-oauth-init.sh
#   # or drop them in a gitignored .env next to this repo, or enter interactively
#
# Prereqs on the Spotify app (developer.spotify.com/dashboard):
#   Redirect URI must include exactly:  http://localhost:8888/callback
#
# The heavy lifting (browser URL, :8888 callback listener, token exchange) is in
# the Rust binary's `oauth-init` subcommand; this wrapper just feeds it creds and
# renders the Secret. Output deploy/secrets.yaml is GITIGNORED — never commit it.
set -euo pipefail

cd "$(dirname "$0")/.."

# Load a local .env if present (gitignored).
[ -f .env ] && set -a && . ./.env && set +a

: "${SPOTIFY_CLIENT_ID:=}"
: "${SPOTIFY_CLIENT_SECRET:=}"
if [ -z "$SPOTIFY_CLIENT_ID" ]; then
  read -r -p "SPOTIFY_CLIENT_ID: " SPOTIFY_CLIENT_ID
fi
if [ -z "$SPOTIFY_CLIENT_SECRET" ]; then
  read -r -s -p "SPOTIFY_CLIENT_SECRET: " SPOTIFY_CLIENT_SECRET; echo
fi
export SPOTIFY_CLIENT_ID SPOTIFY_CLIENT_SECRET

echo ">> building gopher-spot (net feature)..."
cargo build --release >/dev/null

echo ">> running the OAuth flow (a browser URL will be printed)..."
# The binary prints prompts to stderr and 'REFRESH_TOKEN=...' to stdout.
REFRESH_LINE="$(./target/release/gopher-spot oauth-init)"
REFRESH_TOKEN="${REFRESH_LINE#REFRESH_TOKEN=}"
if [ -z "$REFRESH_TOKEN" ] || [ "$REFRESH_TOKEN" = "$REFRESH_LINE" ]; then
  echo "!! no refresh token captured; aborting" >&2
  exit 1
fi

OUT=deploy/secrets.yaml
cat > "$OUT" <<EOF
# GENERATED by scripts/spotify-oauth-init.sh — gitignored, DO NOT COMMIT.
# The Web API OAuth creds consumed by the gopher-spot dcgi (envFrom secretRef).
apiVersion: v1
kind: Secret
metadata:
  name: spotify-oauth
  namespace: gopher-spot
type: Opaque
stringData:
  SPOTIFY_CLIENT_ID: "${SPOTIFY_CLIENT_ID}"
  SPOTIFY_CLIENT_SECRET: "${SPOTIFY_CLIENT_SECRET}"
  SPOTIFY_REFRESH_TOKEN: "${REFRESH_TOKEN}"
EOF

echo ">> wrote $OUT"
echo ">> apply it and restart the server so it picks up the Secret:"
echo "   kubectl apply -f $OUT"
echo "   kubectl rollout restart deployment/gopher-server -n gopher-spot"
